from PIL import Image, ImageDraw

# Load the original background image
img = Image.open('c:/laragon/www/my_vibe/assets/images/lake_guy.png').convert('RGB')
w, h = img.size

# Let's scan specifically for ORANGE/WARM colored pixels (ember glow color)
# which would be R > G > B with high R
# But the source image might not have the ember drawn - it's generated by JS

# Let's look for the WHITE cigarette stick itself  
# A cigarette is white/light gray against dark background
# The end of the cigarette (tip) is where we want the smoke

# From the earlier analysis, the brightest pixel cluster is around x=0.647, y=0.591
# Let's create a large clear view of the region around the suspected cigarette

cx = int(w * 0.62)
cy = int(h * 0.55)
crop_size = 200

x1, y1 = cx - crop_size, cy - crop_size
x2, y2 = cx + crop_size, cy + crop_size

crop = img.crop((x1, y1, x2, y2))
cw, ch = crop.size

# Draw on the crop
draw = ImageDraw.Draw(crop)

# Draw a grid every 2% of original image
for x_pct in range(50, 76, 1):
    cx_pct = int(w * x_pct / 100) - x1
    if 0 <= cx_pct < cw:
        color = (200, 0, 0) if x_pct % 5 == 0 else (60, 0, 0)
        draw.line([(cx_pct, 0), (cx_pct, ch)], fill=color, width=1)
        if x_pct % 5 == 0:
            draw.text((cx_pct + 2, 5), f"{x_pct}%", fill=(255, 0, 0))

for y_pct in range(40, 72, 1):
    cy_pct = int(h * y_pct / 100) - y1
    if 0 <= cy_pct < ch:
        color = (0, 200, 0) if y_pct % 5 == 0 else (0, 60, 0)
        draw.line([(0, cy_pct), (cw, cy_pct)], fill=color, width=1)
        if y_pct % 5 == 0:
            draw.text((5, cy_pct + 2), f"{y_pct}%", fill=(0, 255, 0))

# Mark the current target
cx_mark = int(w * 0.635) - x1
cy_mark = int(h * 0.590) - y1
draw.line([(cx_mark - 8, cy_mark), (cx_mark + 8, cy_mark)], fill=(255, 255, 255), width=2)
draw.line([(cx_mark, cy_mark - 8), (cx_mark, cy_mark + 8)], fill=(255, 255, 255), width=2)
draw.text((cx_mark + 10, cy_mark), "CURRENT (0.635,0.590)", fill=(255, 255, 255))

dest_path = 'C:/Users/LENOVO/.gemini/antigravity-ide/brain/70d14234-39af-44f8-a996-b4b7f4ef5622/cigarette_region_grid.png'
crop.save(dest_path)
print(f"Saved to {dest_path}")
